
public interface PlayersHandbook
{
	public final String HUMAN = "human",
						DWARF = "dwarf",
						ELF = "elf",
						GNOME = "gnome",
						HALF_ELF = "half elf",
						HALF_ORC = "half orc",
						HALFLING = "halfling",
						
						BARBARIAN = "barbarian",
						BARD = "bard",
						CLERIC = "cleric",
						DRUID = "druid",
						FIGHTER = "fighter",
						MONK = "monk",
						PALADIN = "paladin",
						RANGER = "ranger",
						ROGUE = "rogue",
						SORCERER = "sorcerer",
						WIZARD = "wizard",
						
						APPRAISE = "appraise",
						BALANCE = "balance",
						BLUFF = "bluff",
						CLIMB = "climb",
						CONCENTRATION = "concentration",
						CRAFT = "craft",
						DECIPHER_SCRIPT = "decipher script",
						DIPLOMACY = "diplomacy",
						DISABLE_DEVICE = "disable device",
						DISGUISE = "disguise",
						ESCAPE_ARTIST = "escape artist",
						FORGERY = "forgery",
						GATHER_INFORMATION = "gather information",
						HANDLE_ANIMAL = "handle animal",
						HEAL = "heal",
						HIDE = "hide",
						INTIMIDATE = "intimidate",
						JUMP = "jump",
						KNOWLEDGE = "knowledge",
						LISTEN = "listen",
						MOVE_SILENTLY = "move silently",
						OPEN_LOCK = "open lock",
						PERFORM = "perform",
						PROFESSION = "profession",
						RIDE = "ride",
						SEARCH = "search",
						SENSE_MOTIVE = "sense motive",
						SLIGHT_OF_HAND = "slight of hand",
						SPEAK_LANGUAGE = "speak language",
						SPELLCRAFT = "spellcraft",
						SPOT = "spot",
						SURVIVAL = "survival",
						SWIM = "swim",
						TUMBLE = "tumble",
						USE_MAGIC_DEVICE = "use magic device",
						USE_ROPE = "use rope",
						
						ABYSSAL = "abyssal",
						AQUAN = "aquan",
						AURAN = "auran",
						CELESTIAL = "celestial",
						COMMON = "common",
						DRACONIC = "draconic",
						DRUIDIC;
}
